import streamlit as st 
import openai



st.set_page_config(page_title="GPT-3.5 Turbo and DALL-E App", page_icon="🤖", layout="wide")

# Define a function to get the GPT-3.5 response
@st.cache_data
def get_gpt_response(api_key, question):
    openai.api_key = api_key
    response = openai.Completion.create(
        engine="davinci",
        prompt=question,
        max_tokens=150
    )
    return response.choices[0].text.strip()

# Define a function to get the DALL-E image URL
@st.cache_data
def get_dalle_image(api_key, prompt):
    openai.api_key = api_key
    response = openai.Image.create(
        prompt=prompt,
        n=1,
        size="512x512"
    )
    return response['data'][0]['url']

# Sidebar for navigation
page = st.sidebar.selectbox("Select a page", ["GPT-3.5 Chatbot", "DALL-E Image Generator"])

# Common API key input
api_key = st.sidebar.text_input("OpenAI API Key", type="password")
if api_key:
    st.session_state["api_key"] = api_key

# Page 1: GPT-3.5 Chatbot
if page == "GPT-3.5 Chatbot":
    st.title("GPT-3.5 Turbo Chatbot")
    st.write("Enter your OpenAI API key and ask a question.")
    
    question = st.text_input("Enter your question")
    
    if question:
        if "api_key" in st.session_state:
            response = get_gpt_response(st.session_state["api_key"], question)
            st.write("Response from GPT-3.5 Turbo:")
            st.write(response)
        else:
            st.write("Please enter your OpenAI API key.")
    
# Page 2: DALL-E Image Generator
elif page == "DALL-E Image Generator":
    st.title("DALL-E Image Generator")
    st.write("Enter your OpenAI API key and a prompt to generate an image.")
    
    prompt = st.text_input("Enter your prompt")
    
    if prompt:
        if "api_key" in st.session_state:
            image_url = get_dalle_image(st.session_state["api_key"], prompt)
            st.image(image_url, caption="Generated by DALL-E", use_column_width=True)
        else:
            st.write("Please enter your OpenAI API key.")
